
---
- name: Configure EC2 Servers
  hosts: bastion
  become: true

  tasks:

    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - nginx
          - git
          - curl
        state: present

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes
