
---
- name: Configure EC2 Servers
  hosts: bastion
  become: true

  tasks:

    - name: Ensure python3-apt exists
      raw: sudo apt-get update && sudo apt-get install -y python3-apt

    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - nginx
          - git
          - curl
        state: present

    - name: Start nginx
      service:
        name: nginx
        state: started
        enabled: yes
