# ; [nginx]
# ; {{ nginx_private_ip }}

# ; [app]
# ; {{ app_private_ip }}

# ; [all:vars]
# ; ansible_user=ec2-user
# ; ansible_ssh_private_key_file=~/.ssh/mykey.pem

# resource "local_file" "inventory" {
#   content = <<EOF
# [nginx]
# ${aws_instance.nginx.public_ip}

# [app]
# ${aws_instance.app.private_ip}

# [all:vars]
# ansible_user=ec2-user
# ansible_ssh_private_key_file=${var.key_path}
# EOF

#   filename = "${path.module}/ansible/inventory.ini"
# }

; [bastion]
; <BASTION_IP> ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/ec2.pem

; [app]
; <APP_PRIVATE_IP> ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/ec2.pem ansible_ssh_common_args='-o ProxyCommand="ssh -W %h:%p -i ~/.ssh/ec2.pem ec2-user@<BASTION_IP>"'

[bastion]
3.128.170.77 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[app_servers]
10.0.10.144 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_common_args='-o ProxyJump=ubuntu@3.128.170.77'