---
- name: Ansible Deployment
  hosts: all
  become: true
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present
    - name: Install Git
      yum:
        name: git
        state: present
    - name: Install Curl
      yum:
        name: curl
        state: present
    - name: Start Nginx
      service:
        name: nginx
        state: started
        enabled: true
    - name: Deploy index.html
      copy:
        src: ../user_data/index.html
        dest: /usr/share/nginx/html/index.html

- hosts: app
  become: true
  tasks:
    - name: Install Python3 & pip
      yum:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
    - name: Install requirements
      pip:
        requirements: ../user_data/requirements.txt
    - name: Deploy main.py
      copy:
        src: ../user_data/main.py
        dest: /home/ec2-user/main.py
    - name: Start FastAPI
      shell: "nohup python3 /home/ec2-user/main.py &"