name: Terraform + Ansible Deploy
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-2

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: generate variable.tfvars
      working-directory: terraform
      run: |
        cat <<EOF > terraform.tfvars
        key_name = "${{ secrets.TF_VAR_key_name }}"
        db_password = "${{ secrets.TF_VAR_db_password }}"
        domain_name = "${{ secrets.TF_VAR_domain_name }}"
        EOF

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init & Apply
      run: |
        terraform -chdir=terraform init -reconfigure
        terraform -chdir=terraform apply -auto-approve \
          # -var "key_name=${{ secrets.TF_VAR_key_name }}" \
          # -var "db_password=${{ secrets.TF_VAR_db_password }}" \
          # -var "domain_name=${{ secrets.TF_VAR_domain_name }}"
    - name: Get Terraform Outputs
      id: tf
      run: |
        echo "NGINX_IP=$(terraform -chdir=terraform output -raw nginx_ip)" >> $GITHUB_ENV
        echo "APP_IP=$(terraform -chdir=terraform output -raw app_ip)" >> $GITHUB_ENV

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i terraform/inventory.ini playbooks/playbook.yml