name: Terraform + Ansible Deploy
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-2

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init & Apply
      run: |
        terraform -chdir=terraform init -reconfigure
        terraform -chdir=terraform apply -auto-approve \
          -var="ami_id=${{ secrets.AMI_ID }}" \
          -var="key_name=${{ secrets.KEY_NAME }}" \
          -var="db_password=${{ secrets.DB_PASSWORD }}" \
          -var="domain_name=${{ secrets.DOMAIN_NAME }}"

    - name: Install Ansible
      run: |
        sudo apt update
        sudo apt install -y ansible

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i terraform/inventory.ini ansible/playbook.yml